/*
 * Bona vortaro - an Esperanto dictionary for Android, based on PReVo
 * Copyright (C) 2012, 2013, 2016  Neil Roberts
 * Copyright (C) 2026  kotchwane
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 2 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package uk.co.busydoingnothing.prevo

import android.content.Context
import android.graphics.Typeface
import android.text.SpannableString
import android.text.style.ClickableSpan
import android.text.style.QuoteSpan
import android.text.style.RelativeSizeSpan
import android.text.style.StyleSpan
import android.text.style.SuperscriptSpan
import android.util.Log
import android.view.View
import java.util.Locale

/** A section of an article: a derived word or a group of translations. */
class ArticleSection(
    val language: String,
    val header: SpannableString,
    val content: SpannableString,
)

class Article(val title: SpannableString, val sections: List<ArticleSection>)

/* Marks for the parts of the text that the article screen shows in its
 * own way: the kind of word ("transitiva"), its field ("matematiko") and
 * the examples. They don't change how the text is drawn by themselves. */
class GrammarSpan
class FieldSpan
class ExampleSpan

/** The symbol of the type of a link, eg. "↘", with its type as numbered by
 * prevodb (see LinkType). */
class LinkTypeSpan(val type: Int)

/** A link to another section of the same article. The translations use
 * them to point back to the word they translate. */
class SectionLinkSpan(val section: Int, private val onShowSection: (Int) -> Unit) : ClickableSpan() {
    override fun onClick(widget: View) = onShowSection(section)
}

/** Reads the articles generated by prevodb. Each file contains 16
 * articles: article n is the (n & 0xf)th of articles/article-(n >> 4).bin.
 * Each article is a title followed by sections, each one being a language
 * code, a header and a content. Every string is UTF-8 text followed by a
 * list of spans. */
object ArticleLoader {
    private const val TAG = "bonaarticle"

    /* Types of the spans in the files */
    private const val SPAN_REFERENCE = 0
    private const val SPAN_SUPERSCRIPT = 1
    private const val SPAN_ITALIC = 2
    private const val SPAN_QUOTE = 3
    private const val SPAN_BOLD = 4
    /* Added to prevodb in the fork; prevodb without them doesn't write
     * them, and older readers ignore them */
    private const val SPAN_GRAMMAR = 5
    private const val SPAN_FIELD = 6
    private const val SPAN_EXAMPLE = 7
    private const val SPAN_LINK_TYPE = 8

    /**
     * Loads an article, keeping only the sections of the languages shown
     * in the settings (Esperanto is always shown).
     *
     * @param onShowSection called when a link to another section of the
     *   same article is clicked, with the number of the section
     * @param quoteColor colour of the bar drawn next to quotations
     */
    fun load(
        context: Context,
        articleNumber: Int,
        onShowSection: (Int) -> Unit,
        quoteColor: Int,
    ): Article {
        val fileName = String.format(Locale.US, "articles/article-%03xx.bin", articleNumber shr 4)
        val stream = context.assets.open(fileName)
        val input = BinaryReader(stream)

        try {
            skipArticles(input, articleNumber and 0xf)

            val articleLength = input.readInt()
            val articleStart = input.position
            val reader = SpanReader(articleNumber, onShowSection, quoteColor)
            val title = reader.read(input)
            val showTranslations = BonaSettings.translationFilter(context)
            val sections = mutableListOf<ArticleSection>()

            while (input.position - articleStart < articleLength) {
                val language = readLanguageCode(input)

                if (showTranslations(language)) {
                    val header = reader.read(input)
                    val content = reader.read(input)
                    sections.add(ArticleSection(language, header, content))
                } else {
                    skipSpannableString(input)
                    skipSpannableString(input)
                }
            }

            return Article(title, sections)
        } finally {
            stream.close()
        }
    }

    private fun skipArticles(input: BinaryReader, count: Int) {
        repeat(count) {
            input.skip(input.readInt().toLong())
        }
    }

    private fun readLanguageCode(input: BinaryReader): String {
        val buf = ByteArray(3)
        input.readAll(buf)

        var length = buf.size
        while (length > 0 && buf[length - 1] == 0.toByte())
            length--

        return String(buf, 0, length, Charsets.UTF_8)
    }

    private fun skipSpannableString(input: BinaryReader) {
        input.skip(input.readShort().toLong())

        /* Each span is its length, start, two data values and its type */
        while (input.readShort() != 0)
            input.skip(2 + 2 + 2 + 1)
    }

    private class SpanReader(
        val articleNumber: Int,
        val onShowSection: (Int) -> Unit,
        val quoteColor: Int,
    ) {
        fun read(input: BinaryReader): SpannableString {
            val bytes = ByteArray(input.readShort())
            input.readAll(bytes)

            val string = SpannableString(String(bytes, Charsets.UTF_8))

            while (true) {
                val spanLength = input.readShort()
                if (spanLength == 0)
                    break

                val spanStart = input.readShort()
                val data1 = input.readShort()
                val data2 = input.readShort()
                val spanType = input.readByte()
                val spanEnd = spanStart + spanLength

                if (spanStart < 0 || spanLength < 0 || spanEnd > string.length) {
                    /* Skip it instead of crashing in setSpan */
                    Log.wtf(TAG, "Invalid span $spanStart→$spanEnd for string of length ${string.length}")
                    continue
                }

                for (span in createSpans(spanType, data1, data2))
                    string.setSpan(span, spanStart, spanEnd, 0)
            }

            return string
        }

        private fun createSpans(type: Int, data1: Int, data2: Int): List<Any> =
            when (type) {
                SPAN_REFERENCE ->
                    /* data1 is the article and data2 the section */
                    if (data1 == articleNumber)
                        listOf(SectionLinkSpan(data2, onShowSection))
                    else
                        listOf(ReferenceSpan(data1, data2))
                SPAN_SUPERSCRIPT -> listOf(SuperscriptSpan(), RelativeSizeSpan(0.5f))
                SPAN_ITALIC -> listOf(StyleSpan(Typeface.ITALIC))
                SPAN_QUOTE -> listOf(QuoteSpan(quoteColor))
                SPAN_BOLD -> listOf(StyleSpan(Typeface.BOLD))
                SPAN_GRAMMAR -> listOf(GrammarSpan())
                SPAN_FIELD -> listOf(FieldSpan())
                SPAN_EXAMPLE -> listOf(ExampleSpan())
                SPAN_LINK_TYPE -> listOf(LinkTypeSpan(data1))
                else -> emptyList()
            }
    }
}
