#!/usr/bin/env python3
# Generates the launcher icon of the app (see the docstring below).
#
# Usage, from the root of the repository:
#   python3 -m venv /tmp/icon-venv && /tmp/icon-venv/bin/pip install pillow
#   /tmp/icon-venv/bin/python scripts/generate-icon.py app/src/main/res
"""Generate the launcher icon of La bona vortaro: a magnifying glass with
the green star of Esperanto in its lens, on cream paper, in the colours of
the design of the app (see BonaTheme.kt).

Outputs (into the given res/ directory):
  drawable/ic_launcher_foreground.xml   adaptive icon foreground
  drawable/ic_launcher_monochrome.xml   themed icon (Android 13+)
  mipmap-anydpi-v26/ic_launcher.xml     adaptive icon definition
  values/ic_launcher_background.xml     background colour (the paper)
  mipmap-*/ic_launcher.png              legacy icons, before Android 8

The adaptive icon canvas is 108x108; launchers show about its centred 72,
and the safe zone is the centred 66 circle. Only shapes, no font.
"""
import math
import os
import sys

from PIL import Image, ImageDraw

RES = sys.argv[1]

PAPER = "#F4EDDD"   # background
GLASS = "#FFFAEF"   # the lens
INK = "#1F5132"     # rim and handle
STAR = "#0F7A35"    # the green of the flag of Esperanto

# --- The shapes, in 108x108 coordinates (y down) -----------------------------
# The lens, a little up and left so that the handle fits in the safe zone
LENS_X, LENS_Y = 49.8, 49.8
LENS_R = 21.1        # outside of the rim
RIM = 4.8
# The handle, at 45° down to the right, with round ends
HANDLE_ANGLE = math.radians(45)
HANDLE_FROM = LENS_R
HANDLE_TO = LENS_R + 13.4
HANDLE_W = 7.9
# The star in the lens
STAR_X, STAR_Y = 49.8, 50.6
STAR_R = 12.9
STAR_INNER = 0.42


def star_points(cx, cy, r, inner=STAR_INNER):
    points = []
    for i in range(10):
        a = -math.pi / 2 + i * math.pi / 5
        rr = r if i % 2 == 0 else r * inner
        points.append((cx + rr * math.cos(a), cy + rr * math.sin(a)))
    return points


def handle_ends():
    c, s = math.cos(HANDLE_ANGLE), math.sin(HANDLE_ANGLE)
    return ((LENS_X + HANDLE_FROM * c, LENS_Y + HANDLE_FROM * s),
            (LENS_X + HANDLE_TO * c, LENS_Y + HANDLE_TO * s))


def circle_path(cx, cy, r):
    return (f"M{cx - r:.2f},{cy:.2f} a{r:.2f},{r:.2f} 0 1,0 {2 * r:.2f},0 "
            f"a{r:.2f},{r:.2f} 0 1,0 {-2 * r:.2f},0 Z")


def vector(body):
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate-icon.py: a magnifying glass with the
     green star of Esperanto in its lens. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
        android:width="108dp"
        android:height="108dp"
        android:viewportWidth="108"
        android:viewportHeight="108">
{body}</vector>
"""


def fill(d, color):
    return f"""    <path android:fillColor="{color}"
          android:pathData="{d}" />
"""


def stroke(d, color, width):
    return f"""    <path android:strokeColor="{color}"
          android:strokeWidth="{width:.2f}"
          android:strokeLineCap="round"
          android:pathData="{d}" />
"""


(hx0, hy0), (hx1, hy1) = handle_ends()
handle = f"M{hx0:.2f},{hy0:.2f} L{hx1:.2f},{hy1:.2f}"
star = "M" + " L".join(f"{x:.2f},{y:.2f}" for x, y in star_points(STAR_X, STAR_Y, STAR_R)) + " Z"
glass = circle_path(LENS_X, LENS_Y, LENS_R - RIM)
rim = circle_path(LENS_X, LENS_Y, LENS_R - RIM / 2)


def shapes(glass_color, rim_color, star_color):
    body = stroke(handle, rim_color, HANDLE_W)
    if glass_color:
        body += fill(glass, glass_color)
    body += stroke(rim, rim_color, RIM)
    body += fill(star, star_color)
    return body


os.makedirs(f"{RES}/drawable", exist_ok=True)
with open(f"{RES}/drawable/ic_launcher_foreground.xml", "w") as f:
    f.write(vector(shapes(GLASS, INK, STAR)))

# Themed icon: a single colour chosen by the system, the lens left empty
with open(f"{RES}/drawable/ic_launcher_monochrome.xml", "w") as f:
    f.write(vector(shapes(None, "#000000", "#000000")))

os.makedirs(f"{RES}/mipmap-anydpi-v26", exist_ok=True)
with open(f"{RES}/mipmap-anydpi-v26/ic_launcher.xml", "w") as f:
    f.write("""<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
""")

with open(f"{RES}/values/ic_launcher_background.xml", "w") as f:
    f.write(f"""<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="ic_launcher_background">{PAPER}</color>
</resources>
""")


# --- Legacy icons: the same shapes on a round paper background, drawn large
# and scaled down. They show the centred 72 of the canvas, like launchers.
def legacy(size):
    big = 1024
    k = big / 72.0  # 72 icon units fill the image

    def p(x, y):
        return ((x - 18) * k, (y - 18) * k)

    im = Image.new("RGBA", (big, big), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    d.ellipse([0, 0, big - 1, big - 1], fill=PAPER)
    w = HANDLE_W * k
    d.line([p(hx0, hy0), p(hx1, hy1)], fill=INK, width=round(w))
    for x, y in (p(hx0, hy0), p(hx1, hy1)):
        d.ellipse([x - w / 2, y - w / 2, x + w / 2, y + w / 2], fill=INK)
    cx, cy = p(LENS_X, LENS_Y)
    r = LENS_R * k
    d.ellipse([cx - r, cy - r, cx + r, cy + r], fill=INK)
    r = (LENS_R - RIM) * k
    d.ellipse([cx - r, cy - r, cx + r, cy + r], fill=GLASS)
    d.polygon([p(x, y) for x, y in star_points(STAR_X, STAR_Y, STAR_R)], fill=STAR)
    return im.resize((size, size), Image.LANCZOS)


for density, size in [("mdpi", 48), ("hdpi", 72), ("xhdpi", 96), ("xxhdpi", 144), ("xxxhdpi", 192)]:
    os.makedirs(f"{RES}/mipmap-{density}", exist_ok=True)
    legacy(size).save(f"{RES}/mipmap-{density}/ic_launcher.png")
